spring:
  liquibase:
    change-log: db/changelog/changelog.yml
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:file:./data/shareit
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
