CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE ITEMS
(
    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NAME        VARCHAR(255)                            NOT NULL,
    DESCRIPTION VARCHAR(512)                            NOT NULL,
    AVAILABLE   BOOLEAN                                 NOT NULL,
    OWNER_ID    BIGINT                                  NOT NULL,
    REQUEST     varchar,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_item_owner FOREIGN KEY (OWNER_ID) REFERENCES USERS (ID)
);

CREATE TABLE BOOKINGS
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    START_DATE TIMESTAMP                               NOT NULL,
    END_DATE   TIMESTAMP                               NOT NULL,
    ITEM_ID    BIGINT                                  NOT NULL,
    BOOKER_ID  BIGINT                                  NOT NULL,
    STATUS     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking_item FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID),
    CONSTRAINT fk_booking_user FOREIGN KEY (BOOKER_ID) REFERENCES USERS (ID)
);

CREATE TABLE COMMENTS
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TEXT      VARCHAR(512)                            NOT NULL,
    ITEM_ID   BIGINT                                  NOT NULL,
    AUTHOR_ID BIGINT                                  NOT NULL,
    CREATED   TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_item FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID),
    CONSTRAINT fk_comment_user FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID)
)
